/**
 * VMO Tactics - Monster Database
 * Version: 1.1 (Cleaned & Normalized)
 */

window.dbMonsters = [
  {
    "id": 1,
    "name": "フレイミー",
    "type": "fire",
    "img": "/img/monsters/001_flamy.webp",
    "rarity": 1,
    "stats": { "hp": 130, "atk": 115, "def": 65, "spd": 130, "range": 1 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "アクセルステップ", "カウンター", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "炎のネズミ。\n素早い動きで敵を翻弄し、噛みついて燃やし尽くす。"
  },
  {
    "id": 2,
    "name": "エンガール",
    "type": "fire",
    "img": "/img/monsters/002_engirl.webp",
    "rarity": 2,
    "stats": { "hp": 150, "atk": 120, "def": 80, "spd": 90, "range": 2 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "クイックファイア", "パワーチャージ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "highest_atk", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "炎を操る少女。\n出す炎の色でその日の彼女の調子がわかるらしい。"
  },
  {
    "id": 3,
    "name": "ウォータル",
    "type": "water",
    "img": "/img/monsters/003_wartle.webp",
    "rarity": 2,
    "stats": { "hp": 200, "atk": 65, "def": 130, "spd": 40, "range": 1 },
    "moves": ["アクアストリーム", "マッドウェーブ", "アイアンシェル", "インティミデイト", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "hp_below_50", "preferred_skill": 2 },
    "desc": "大きなカメ型モンスター。\n動きは鈍重だが、その身体は非常に硬い。"
  },
  {
    "id": 4,
    "name": "スイネーク",
    "type": "water",
    "img": "/img/monsters/004_swinake.webp",
    "rarity": 2,
    "stats": { "hp": 160, "atk": 105, "def": 95, "spd": 80, "range": 1 },
    "moves": ["アクアストリーム", "マッドウェーブ", "アシッドボム", "ドレインバイト", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 3 },
    "desc": "水の力を操る大蛇。\n咬まれたら生気を吸われると言われている。"
  },
  {
    "id": 5,
    "name": "ハッパンク",
    "type": "grass",
    "img": "/img/monsters/005_happank.webp",
    "rarity": 2,
    "stats": { "hp": 180, "atk": 95, "def": 110, "spd": 50, "range": 1 },
    "moves": ["ソーンウィップ", "カッターウィンド", "スパイダーネット", "アイアンシェル", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "棘を纏った恐竜のようなモンスター。\n怒ると手が付けられない。"
  },
  {
    "id": 6,
    "name": "リーファム",
    "type": "grass",
    "img": "/img/monsters/006_leafam.webp",
    "rarity": 1,
    "stats": { "hp": 120, "atk": 90, "def": 70, "spd": 140, "range": 2 },
    "moves": ["ソーンウィップ", "カッターウィンド", "アクセルステップ", "ヒールライト", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "自然の力をあやつるトリ。\n速すぎて並の人間ではその動きを追うことすらできないという。"
  },
  {
    "id": 7,
    "name": "ライトラ",
    "type": "light",
    "img": "/img/monsters/007_lightra.webp",
    "rarity": 3,
    "stats": { "hp": 150, "atk": 125, "def": 75, "spd": 110, "range": 1 },
    "moves": ["ホーリーレイ", "フラッシュバン", "光速の爪", "パワーチャージ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "highest_atk", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "光の力を手に入れたトラ。\nどんな相手にも勇敢に立ち向かう。"
  },
  {
    "id": 8,
    "name": "アカリード",
    "type": "light",
    "img": "/img/monsters/008_akarid.webp",
    "rarity": 2,
    "stats": { "hp": 140, "atk": 70, "def": 120, "spd": 100, "range": 2 },
    "moves": ["ホーリーレイ", "フラッシュバン", "インティミデイト", "ヒールライト", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "ally_hp_below_50", "preferred_skill": 3 },
    "desc": "光の妖精。\n輝くオーラで味方に癒しを与える。"
  },
  {
    "id": 9,
    "name": "エルダーク",
    "type": "dark",
    "img": "/img/monsters/009_eldark.webp",
    "rarity": 2,
    "stats": { "hp": 130, "atk": 150, "def": 80, "spd": 60, "range": 2 },
    "moves": ["ダークインパクト", "ダークミスト", "カースドノヴァ", "パワーチャージ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "闇の魔導士。\n彼はその禍々しい力を一体何に使うのだろうか……。"
  },
  {
    "id": 10,
    "name": "ザルディヴァ",
    "type": "dark",
    "img": "/img/monsters/010_zaldiva.webp",
    "rarity": 3,
    "stats": { "hp": 170, "atk": 95, "def": 110, "spd": 45, "range": 1 },
    "moves": ["ダークインパクト", "ダークミスト", "ディストーション", "インティミデイト", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "影に潜むオオカミ。\n空間を操る不思議な技を使うという。"
  },
  {
    "id": 11,
    "name": "マグマス",
    "type": "fire",
    "img": "/img/monsters/011_magmas.webp",
    "rarity": 3,
    "stats": { "hp": 190, "atk": 65, "def": 125, "spd": 20, "range": 1 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "マグマブロック", "パワーチャージ", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "マグマの巨人。\n敵の攻撃を受けながらも前進するタフな身体を持つ。"
  },
  {
    "id": 12,
    "name": "イグニルフ",
    "type": "fire",
    "img": "/img/monsters/012_ignilf.webp",
    "rarity": 2,
    "stats": { "hp": 120, "atk": 90, "def": 90, "spd": 125, "range": 1 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "インティミデイト", "アシッドボム", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "炎を纏うオオカミ。\nその燃えるような眼差しは敵の戦意を奪う。"
  },
  {
    "id": 13,
    "name": "レイコーン",
    "type": "water",
    "img": "/img/monsters/013_raycorn.webp",
    "rarity": 3,
    "stats": { "hp": 140, "atk": 130, "def": 60, "spd": 100, "range": 1 },
    "moves": ["アクアストリーム", "アイスホーン", "ドレインホーン", "アクセルステップ", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "highest_atk", "skill_condition": "always", "preferred_skill": 1 },
    "desc": "氷を操るユニコーン。\n優雅な姿で水上を駆けるが、戦闘時はそのツノで敵を串刺しにする。"
  },
  {
    "id": 14,
    "name": "コペゾー",
    "type": "water",
    "img": "/img/monsters/014_copezo.webp",
    "rarity": 2,
    "stats": { "hp": 170, "atk": 90, "def": 115, "spd": 60, "range": 1 },
    "moves": ["アクアストリーム", "マッドウェーブ", "ヒールライト", "ハーフカット", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "nearest", "skill_condition": "ally_hp_below_50", "preferred_skill": 2 },
    "desc": "子供に見えるが実は大人のペンギン型モンスター。\n羽毛に覆われたその身体は意外とタフだ。"
  },
  {
    "id": 15,
    "name": "グラシオン",
    "type": "grass",
    "img": "/img/monsters/015_glacion.webp",
    "rarity": 3,
    "stats": { "hp": 180, "atk": 145, "def": 65, "spd": 75, "range": 1 },
    "moves": ["ソーンウィップ", "カッターウィンド", "グラスファング", "パワーチャージ", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "自然の力を味方につけた百獣の王。\nその力は凄まじく、鋼鉄ですら噛み砕くという。"
  },
  {
    "id": 16,
    "name": "ツルギ",
    "type": "grass",
    "img": "/img/monsters/016_tsurugi.webp",
    "rarity": 2,
    "stats": { "hp": 125, "atk": 120, "def": 85, "spd": 100, "range": 1 },
    "moves": ["ソーンウィップ", "カッターウィンド", "ハーフカット", "カウンター", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "highest_atk", "skill_condition": "random", "preferred_skill": 2 },
    "desc": "自然の力を武器に変える剣士。\n草の刀を使ったトリッキーな動きで敵を翻弄する。"
  },
  {
    "id": 17,
    "name": "ボルクマ",
    "type": "light",
    "img": "/img/monsters/017_volkuma.webp",
    "rarity": 3,
    "stats": { "hp": 160, "atk": 125, "def": 85, "spd": 55, "range": 1 },
    "moves": ["ホーリーレイ", "フラッシュバン", "ボルトクロー", "パワーチャージ", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "雷に撃たれて覚醒したクマ。\n電気の力で強化された肉体から放たれる一撃は、相手を感電させる前にあの世へ送る。"
  },
  {
    "id": 18,
    "name": "リフェロス",
    "type": "light",
    "img": "/img/monsters/018_liferos.webp",
    "rarity": 4,
    "stats": { "hp": 150, "atk": 100, "def": 100, "spd": 95, "range": 3 },
    "moves": ["ホーリーレイ", "フラッシュバン", "アルティメットレイ", "ディストーション", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "enemies_gt_2", "preferred_skill": 2 },
    "desc": "ついに完成した龍のモンスター。\n硬化した翼で身を守り、圧倒的な光の力で周囲を焼き尽くす。"
  },
  {
    "id": 19,
    "name": "フィンレーツ",
    "type": "dark",
    "img": "/img/monsters/019_finlates.webp",
    "rarity": 2,
    "stats": { "hp": 110, "atk": 130, "def": 50, "spd": 135, "range": 1 },
    "moves": ["キラーダイブ", "ダークミスト", "アクアダッシュ", "パワーチャージ", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "target_hp_full", "preferred_skill": 0 },
    "desc": "闇の力を与えすぎて悪魔化したイルカ。\n音もなく移動し、油断している相手の隙をついてその首を刎ねる。"
  },
  {
    "id": 20,
    "name": "デヴィートル",
    "type": "dark",
    "img": "/img/monsters/020_deveetle.webp",
    "rarity": 3,
    "stats": { "hp": 160, "atk": 100, "def": 100, "spd": 70, "range": 1 },
    "moves": ["ダークインパクト", "ダークミスト", "ドレインホーン", "アイアンシェル", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "nearest", "skill_condition": "hp_below_50", "preferred_skill": 2 },
    "desc": "自ら悪魔の力を欲したカブトムシ。その欲は尽きることなく、自慢のツノを次から次へと突き刺し、敵の生命力を奪い取る。"
  },
  {
    "id": 21,
    "name": "ミレメント",
    "type": "normal",
    "img": "/img/monsters/021_milement.webp",
    "rarity": 3,
    "stats": { "hp": 150, "atk": 95, "def": 95, "spd": 95, "range": 2 },
    "moves": ["フレイムバースト", "アクアストリーム", "ソーンウィップ", "ホーリーレイ", "ダークインパクト", "プロテクション"],
    "behavior": { "priority": "weakness", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "すべての属性の力をそのツノに植え付けられたカメレオン。体内に宿る属性同士が反発し、時々苦しむ姿が確認されている。"
  },
  {
    "id": 22,
    "name": "フラビット",
    "type": "grass",
    "img": "/img/monsters/022_flabbit.webp",
    "rarity": 2,
    "stats": { "hp": 180, "atk": 100, "def": 120, "spd": 45, "range": 1 },
    "moves": ["ソーンウィップ", "カッターウィンド", "ヒールライト", "疾風の棘", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "nearest", "skill_condition": "ally_hp_below_50", "preferred_skill": 2 },
    "desc": "自然の力を得たウサギ。\n50km離れた場所からでも音を聞き取れるが、大きな音ですぐ気絶する。"
  },
  {
    "id": 23,
    "name": "ベルフレム",
    "type": "fire",
    "img": "/img/monsters/023_bellflem.webp",
    "rarity": 3,
    "stats": { "hp": 160, "atk": 135, "def": 95, "spd": 45, "range": 1 },
    "moves": ["ヘルブレード", "ヒートウェーブ", "ハーフカット", "パワーチャージ", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "炎の剣に宿る精霊が具現化。\n動きは遅いが、その一撃は鐘の音のように重く響く。"
  },
  {
    "id": 24,
    "name": "オヌ・リン",
    "type": "light",
    "img": "/img/monsters/024_onurin.webp",
    "rarity": 3,
    "stats": { "hp": 150, "atk": 120, "def": 100, "spd": 80, "range": 1 },
    "moves": ["ホーリーレイ", "フラッシュバン", "ドレインホーン", "アイスホーン", "ラッシュ", "プロテクション"],
    "behavior": { "priority": "highest_atk", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "光を司る四足歩行のモンスター。\nそのツノの輝きは見たものを圧倒する。"
  },
  {
    "id": 25,
    "name": "ロクザール",
    "type": "fire",
    "img": "/img/monsters/025_rockzaru.webp",
    "rarity": 2,
    "stats": { "hp": 150, "atk": 120, "def": 80, "spd": 80, "range": 1 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "アシッドボム", "ロックパンチ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 3 },
    "desc": "岩のような皮膚を持つサル。\n驚異的な攻撃力で敵を殴り飛ばす。"
  },
  {
    "id": 26,
    "name": "ペパザール",
    "type": "water",
    "img": "/img/monsters/026_paperzaru.webp",
    "rarity": 2,
    "stats": { "hp": 150, "atk": 80, "def": 120, "spd": 80, "range": 1 },
    "moves": ["アクアストリーム", "マッドウェーブ", "インティミデイト", "アクアブロック", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 3 },
    "desc": "手を大きく開いているサル。\nその手は全ての攻撃を吸収し、敵を叩き潰す。"
  },
  {
    "id": 27,
    "name": "シザール",
    "type": "grass",
    "img": "/img/monsters/027_scizaru.webp",
    "rarity": 2,
    "stats": { "hp": 150, "atk": 80, "def": 80, "spd": 120, "range": 1 },
    "moves": ["ソーンウィップ", "カッターウィンド", "足払い", "グラスダッシュ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "両腕が鋭利なハサミになっているサル。\n素早い動きで敵を切断する。"
  },
  {
    "id": 28,
    "name": "ジェケイダ",
    "type": "fire",
    "img": "/img/monsters/028_jetcada.webp",
    "rarity": 2,
    "stats": { "hp": 130, "atk": 90, "def": 70, "spd": 150, "range": 2 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "クイックファイア", "アクセルステップ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "臀部の噴射口から火を吹き出し飛行するセミ。\n最高速度は音速を超えるという。"
  },
  {
    "id": 29,
    "name": "ハナーネ",
    "type": "grass",
    "img": "/img/monsters/029_hanane.webp",
    "rarity": 3,
    "stats": { "hp": 180, "atk": 75, "def": 125, "spd": 70, "range": 2 },
    "moves": ["ソーンウィップ", "カッターウィンド", "アシッドボム", "花粉爆発", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "highest_atk", "skill_condition": "enemies_gt_2", "preferred_skill": 3 },
    "desc": "巨大な花がついた温厚なモンスター。\n外敵から身を守るための硬い外皮を持つ。"
  },
  {
    "id": 30,
    "name": "ビョウゲツ",
    "type": "water",
    "img": "/img/monsters/030_byogetsu.webp",
    "rarity": 2,
    "stats": { "hp": 140, "atk": 110, "def": 90, "spd": 110, "range": 1 },
    "moves": ["アクアストリーム", "マッドウェーブ", "アクセルステップ", "ハーフカット", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 3 },
    "desc": "月のような耳を持つネコ。\n静寂の中に鋭い一撃を隠し持つ。"
  },
  {
    "id": 31,
    "name": "シカバラス",
    "type": "normal",
    "img": "/img/monsters/031_shikabarasu.webp",
    "rarity": 2,
    "stats": { "hp": 150, "atk": 80, "def": 110, "spd": 75, "range": 2 },
    "moves": ["カッターウィンド", "ダークミスト", "ディストーション", "パワーチャージ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "highest_atk", "skill_condition": "turn_1", "preferred_skill": 2 },
    "desc": "こっそりと死骸を食べて生活するカラス。\n凶悪な見た目だが、意外と臆病。"
  },
  {
    "id": 32,
    "name": "オベアー",
    "type": "dark",
    "img": "/img/monsters/032_obear.webp",
    "rarity": 4,
    "stats": { "hp": 190, "atk": 135, "def": 95, "spd": 30, "range": 1 },
    "moves": ["ダークインパクト", "ダークミスト", "ダークファング", "パワーチャージ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "闇を纏った巨大なクマ。\nガラクタを集めて身体に取り付ける。"
  },
  {
    "id": 33,
    "name": "シャコマル",
    "type": "water",
    "img": "/img/monsters/033_shakomaru.webp",
    "rarity": 3,
    "stats": { "hp": 145, "atk": 150, "def": 90, "spd": 65, "range": 1 },
    "moves": ["アクアストリーム", "マッドウェーブ", "スパイラルブロウ", "アクアダッシュ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "target_hp_full", "preferred_skill": 2 },
    "desc": "水圧を操り、圧倒的破壊力を見せつける。\n強靭な殻と素早いパンチで相手を一撃ノックアウト。"
  },
  {
    "id": 34,
    "name": "リュミエット",
    "type": "light",
    "img": "/img/monsters/034_ryumietto.webp",
    "rarity": 2,
    "stats": { "hp": 140, "atk": 120, "def": 75, "spd": 100, "range": 2 },
    "moves": ["ホーリーレイ", "フラッシュバン", "ドレインバイト", "カッターウィンド", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "hp_below_50", "preferred_skill": 2 },
    "desc": "光輝くコウモリ。\n翼を震わせて残像を生み出す。"
  },
  {
    "id": 40,
    "name": "ジェリスタル",
    "type": "water",
    "img": "/img/monsters/040_jellystal.webp",
    "rarity": 3,
    "stats": { "hp": 200, "atk": 80, "def": 100, "spd": 50, "range": 2 },
    "moves": ["アクアストリーム", "マッドウェーブ", "アイアンシェル", "ヒールライト", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "ally_hp_below_50", "preferred_skill": 3 },
    "desc": "水晶の輝きを放つクラゲ。\n触れるものすべてを拒絶する鉄壁の防御を誇る。"
  },
  {
    "id": 41,
    "name": "ヒノエナガ",
    "type": "fire",
    "img": "/img/monsters/041_hinoenaga.webp",
    "rarity": 2,
    "stats": { "hp": 120, "atk": 110, "def": 90, "spd": 90, "range": 2 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "ぱちぱちパーティ", "アクセルステップ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "enemies_gt_2", "preferred_skill": 2 },
    "desc": "尻尾が発火しているトリ。\n100匹以上の群れを成し、一斉に花火を放って騒ぎまくる。"
  },
  {
    "id": 43,
    "name": "アルブラン",
    "type": "grass",
    "img": "/img/monsters/043_albran.webp",
    "rarity": 3,
    "stats": { "hp": 110, "atk": 115, "def": 130, "spd": 100, "range": 3 },
    "moves": ["ソーンウィップ", "カッターウィンド", "ポイズンアロー", "カウンター", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "自然の力を操るアルパカの狩人。\n少しキザな性格だが、放たれる矢は確実に獲物を射抜く。"
  },
  {
    "id": 44,
    "name": "エルシェント",
    "type": "light",
    "img": "/img/monsters/044_elshent.webp",
    "rarity": 4,
    "stats": { "hp": 170, "atk": 100, "def": 110, "spd": 45, "range": 1 },
    "moves": ["ホーリーレイ", "フラッシュバン", "セイントスタンプ", "インティミデイト", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "光に包まれる高貴なゾウ。\nこのモンスターの体重を測れるデバイスは施設にも存在しない。"
  },
  {
    "id": 45,
    "name": "ハリースト",
    "type": "dark",
    "img": "/img/monsters/045_harrist.webp",
    "rarity": 3,
    "stats": { "hp": 120, "atk": 85, "def": 110, "spd": 145, "range": 1 },
    "moves": ["ダークインパクト", "ダークミスト", "ひっくりダイス", "クイックシャドウ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "turn_1", "preferred_skill": 2 },
    "desc": "悪戯好きのハリネズミが霊体にされた。\n色々なものをひっくり返しながら施設を走り回る。"
  },
  {
    "id": 46,
    "name": "バラビィ",
    "type": "fire",
    "img": "/img/monsters/046_baraby.webp",
    "rarity": 3,
    "stats": { "hp": 130, "atk": 130, "def": 85, "spd": 105, "range": 1 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "ドレインローズ", "アクセルステップ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "hp_below_50", "preferred_skill": 2 },
    "desc": "薔薇の香りと炎を振り撒くウサギ。\n情熱的なステップで戦場を赤く染める。"
  },
  {
    "id": 48,
    "name": "モモ",
    "type": "grass",
    "img": "/img/monsters/048_momo.webp",
    "rarity": 2,
    "stats": { "hp": 150, "atk": 85, "def": 120, "spd": 100, "range": 2 },
    "moves": ["ソーンウィップ", "カッターウィンド", "グラスヒール", "スパイダーネット", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "ally_hp_below_50", "preferred_skill": 2 },
    "desc": "心優しいモモンガ。\n自然の力で仲間を癒す。"
  },
  {
    "id": 49,
    "name": "ツキネ",
    "type": "light",
    "img": "/img/monsters/049_tsukine.webp",
    "rarity": 2,
    "stats": { "hp": 125, "atk": 90, "def": 85, "spd": 140, "range": 1 },
    "moves": ["ホーリーレイ", "フラッシュバン", "ハーフカット", "パワーチャージ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "月の輝きに魅せられたキツネ。\n夜空を駆けるような軽やかな身のこなしを見せる。"
  },
  {
    "id": 50,
    "name": "ウィデビット",
    "type": "dark",
    "img": "/img/monsters/050_widevit.webp",
    "rarity": 3,
    "stats": { "hp": 120, "atk": 110, "def": 110, "spd": 100, "range": 2 },
    "moves": ["ダークインパクト", "ダークミスト", "ダウンダイス", "アシッドボム", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "highest_atk", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "知恵を蓄えた闇のモンスター。\n重厚な魔力で敵の自由を奪う。"
  },
  {
    "id": 51,
    "name": "アッピオン",
    "type": "fire",
    "img": "/img/monsters/051_appion.webp",
    "rarity": 3,
    "stats": { "hp": 150, "atk": 120, "def": 100, "spd": 35, "range": 1 },
    "moves": ["フレイムバースト", "ヒートウェーブ", "ポイズンスプレー", "アイアンシェル", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "nearest", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "燃える果実のような頭を持つサソリ。\n尻尾の先から猛毒を放ち、倒れた敵を捕食する。"
  },
  {
    "id": 52,
    "name": "ユッキング",
    "type": "water",
    "img": "/img/monsters/052_yukking.webp",
    "rarity": 4,
    "stats": { "hp": 160, "atk": 110, "def": 115, "spd": 65, "range": 2 },
    "moves": ["アクアストリーム", "マッドウェーブ", "猛吹雪", "ディストーション", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "雪を支配するユキダルマ。\n冷たい吹雪と激しい濁流を自在に操る。"
  },
  {
    "id": 53,
    "name": "シバフールー",
    "type": "grass",
    "img": "/img/monsters/053_shibafulue.webp",
    "rarity": 3,
    "stats": { "hp": 155, "atk": 80, "def": 125, "spd": 70, "range": 1 },
    "moves": ["ソーンウィップ", "カッターウィンド", "もふガード", "花粉爆発", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "自然を纏うヒツジ\nそのもふもふは全ての攻撃を吸収する。"
  },
  {
    "id": 54,
    "name": "ストロビー",
    "type": "light",
    "img": "/img/monsters/054_strawbee.webp",
    "rarity": 2,
    "stats": { "hp": 135, "atk": 130, "def": 80, "spd": 85, "range": 1 },
    "moves": ["ホーリーレイ", "フラッシュバン", "ライトブレード", "ハーフカット", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "甘い香りを放つハチの戦士。\n鋭い針には凝縮された光のエネルギーが宿っている。"
  },
  {
    "id": 55,
    "name": "モスパーク",
    "type": "dark",
    "img": "/img/monsters/055_mospark.webp",
    "rarity": 2,
    "stats": { "hp": 140, "atk": 90, "def": 55, "spd": 125, "range": 2 },
    "moves": ["ダークインパクト", "ダークミスト", "弱点解析", "クイックシャドウ", "プロテクション", "ラッシュ"],
    "behavior": { "priority": "weakness", "skill_condition": "always", "preferred_skill": 2 },
    "desc": "闇の火花を散らしながら舞うガ。\nその羽ばたきは不吉な予兆とされる。"
  },
  {
    "id": 999,
    "name": "ヴァーサス",
    "type": "normal",
    "img": "/img/monsters/999_versus.webp",
    "rarity": 5,
    "stats": { "hp": 9999, "atk": 150, "def": 150, "spd": 150, "range": 3 },
    "moves": ["アルティメットレイ", "カースドノヴァ", "ディストーション", "フレイムバースト", "アクアストリーム", "ソーンウィップ", "ホーリーレイ", "ダークインパクト"],
    "behavior": { "priority": "lowest_hp", "skill_condition": "always", "preferred_skill": 0 },
    "desc": "VMOの世界を管理者として守護する存在。\n彼はこの世界の全てを知っている。"
  }
];
